In [1]:
import numpy as np
import pandas as pd
import time

In [2]:
file_path = "UCI_Credit_Card.csv"

In [3]:
data = pd.read_csv(file_path)

In [4]:
print(data)

          ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0          1    20000.0    2          2         1   24      2      2     -1   
1          2   120000.0    2          2         2   26     -1      2      0   
2          3    90000.0    2          2         2   34      0      0      0   
3          4    50000.0    2          2         1   37      0      0      0   
4          5    50000.0    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996   220000.0    1          3         1   39      0      0      0   
29996  29997   150000.0    1          3         2   43     -1     -1     -1   
29997  29998    30000.0    1          2         2   37      4      3      2   
29998  29999    80000.0    1          3         1   41      1     -1      0   
29999  30000    50000.0    1          2         1   46      0      0      0   

       PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6 

In [5]:
column_names = data.columns

In [6]:
print(column_names)

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default.payment.next.month'],
      dtype='object')


In [7]:
X1 =  data['LIMIT_BAL'].values #
X2 =  data['SEX'].values
X3 =  data['EDUCATION'].values
X4 =  data['MARRIAGE'].values
X5 =  data['AGE'].values       #
X6 =  data['PAY_0'].values
X7 =  data['PAY_2'].values
X8 =  data['PAY_3'].values
X9 =  data['PAY_4'].values
X10 = data['PAY_5'].values
X11 = data['PAY_6'].values
X12 = data['BILL_AMT1'].values #
X13 = data['BILL_AMT2'].values #
X14 = data['BILL_AMT3'].values #
X15 = data['BILL_AMT4'].values #
X16 = data['BILL_AMT5'].values #
X17 = data['BILL_AMT6'].values #
X18 = data['PAY_AMT1'].values  #
X19 = data['PAY_AMT2'].values  #
X20 = data['PAY_AMT3'].values  #
X21 = data['PAY_AMT4'].values  #
X22 = data['PAY_AMT5'].values  #
X23 = data['PAY_AMT6'].values  #

In [342]:
def normalize(column_vector):
    max_value = np.max(column_vector)
    min_value= np.std(column_vector)
    normalized = (column_vector - min_value)/(max_value-min_value)
    return normalized

In [343]:
n = 30000
p = 24
ones = np.ones(n)
ones = np.reshape(ones,(n,1))
X = np.column_stack((ones,normalize(X1),normalize(X2),  normalize(X3), normalize(X4), normalize(X5), normalize(X6),\
                          normalize(X7),normalize(X8),  normalize(X9), normalize(X10),normalize(X11),normalize(X12),\
                          normalize(X13),normalize(X14),normalize(X15),normalize(X16),normalize(X17),\
                          normalize(X18),normalize(X19),normalize(X20),normalize(X21),normalize(X22),\
                          normalize(X23)))
                          
#X = np.column_stack((ones,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,X21,X22,X23))

print(X)
print(X.shape)

[[ 1.         -0.12610736  1.         ... -0.02587976 -0.03715019
  -0.03479655]
 [ 1.         -0.01119845  1.         ... -0.02422778 -0.03715019
  -0.03088181]
 [ 1.         -0.04567112  1.         ... -0.02422778 -0.03471859
  -0.02500969]
 ...
 [ 1.         -0.11461647  0.33813361 ... -0.01894144 -0.03228698
  -0.0287287 ]
 [ 1.         -0.05716201  0.33813361 ... -0.02269804  0.09163735
  -0.03126545]
 [ 1.         -0.09163469  0.33813361 ... -0.02422778 -0.03471859
  -0.03283918]]
(30000, 24)


In [344]:
Y = data['default.payment.next.month'].values

In [345]:
Y = np.reshape(Y,(30000,1))
print(Y.shape)

(30000, 1)


In [346]:
print(X)
print(X.shape)

[[ 1.         -0.12610736  1.         ... -0.02587976 -0.03715019
  -0.03479655]
 [ 1.         -0.01119845  1.         ... -0.02422778 -0.03715019
  -0.03088181]
 [ 1.         -0.04567112  1.         ... -0.02422778 -0.03471859
  -0.02500969]
 ...
 [ 1.         -0.11461647  0.33813361 ... -0.01894144 -0.03228698
  -0.0287287 ]
 [ 1.         -0.05716201  0.33813361 ... -0.02269804  0.09163735
  -0.03126545]
 [ 1.         -0.09163469  0.33813361 ... -0.02422778 -0.03471859
  -0.03283918]]
(30000, 24)


In [347]:
def logistic_function(X_row,Beta):
    result = 1/(1 + np.exp(-np.dot(X_row,Beta)))
    return result

In [348]:
Beta = np.zeros((24,1))
Pi_vector = np.exp(np.dot(X,Beta))/(ones + np.exp(np.dot(X,Beta)))
Pi_complement = ones - Pi_vector
print(Pi_vector.shape)
print(Pi_complement.shape)

(30000, 1)
(30000, 1)


In [349]:
W_matrix = np.eye(X.shape[0])
diagonal_indices = np.diag_indices_from(W_matrix)
diagonal_values = np.multiply(Pi_vector, Pi_complement)
diagonal_values = diagonal_values.flatten()
print(diagonal_values.shape)
W_matrix[diagonal_indices] = diagonal_values
print(W_matrix)
print(W_matrix.shape)

(30000,)
[[0.25 0.   0.   ... 0.   0.   0.  ]
 [0.   0.25 0.   ... 0.   0.   0.  ]
 [0.   0.   0.25 ... 0.   0.   0.  ]
 ...
 [0.   0.   0.   ... 0.25 0.   0.  ]
 [0.   0.   0.   ... 0.   0.25 0.  ]
 [0.   0.   0.   ... 0.   0.   0.25]]
(30000, 30000)


In [350]:
def newton_raphson(Y,X_matrix,Beta):

    error = 0.001
    ones = np.ones(X_matrix.shape[0])
    ones = np.reshape(ones,(X_matrix.shape[0],1))
    Beta_new = Beta
    Beta_old = Beta
    Beta_old2 = Beta
    
    max_iteration = 20
    count = 0
    
    while count != max_iteration:

        Beta_old2 = Beta_old
        
        # Calculate Pi_vector
        Pi_vector = np.exp(np.dot(X_matrix, Beta)) / (1 + np.exp(np.dot(X_matrix, Beta)))
        Pi_complement = ones - Pi_vector
        
        # Update W_matrix
        W_matrix = np.eye(X_matrix.shape[0])
        diagonal_indices = np.diag_indices_from(W_matrix)
        diagonal_values = np.multiply(Pi_vector, Pi_complement)
        diagonal_values = diagonal_values.flatten()
        W_matrix[diagonal_indices] = diagonal_values
        
        # Update Beta_new using Newton-Raphson update rule
        X_t = np.transpose(X_matrix) 
        A = np.dot(np.dot(X_t, W_matrix), X_matrix)
        A_inv = np.linalg.inv(A)
        
        Beta_new = Beta_old + np.dot(np.dot(A_inv, X_t), (Y - Pi_vector))
        
        Beta_old = Beta_new
        count += 1
        
        if np.all(Beta_new - Beta_old) < error:
            break

    print(count)
    return Beta_new


In [351]:
def gradient_descent(Y,X,Beta):

    learning_rate = 0.01
    error = 0.001
    Beta_new = Beta
    Beta_old = Beta
    Beta_old2 = Beta

    max_iteration = 1000
    count = 0
    
    X_t = np.transpose(X)

    while count != max_iteration:

        Beta_old2 = Beta_old

        # Calculate Pi_vector
        Pi_vector = np.exp(np.dot(X, Beta)) / (1 + np.exp(np.dot(X, Beta)))

        Beta_new = Beta_old - learning_rate*np.dot(X_t,(Y - Pi_vector))

        Beta_old = Beta_new
        count += 1
        
        if np.linalg.norm(Beta_new - Beta_old2) < error:
            break

    print(count)
    return Beta_new

In [364]:
result = newton_raphson(Y,X,Beta)
print(result)

1
[[-0.47873572]
 [-0.3151423 ]
 [-0.0878206 ]
 [-0.31523383]
 [-0.23612257]
 [ 0.39343213]
 [ 2.63236631]
 [ 0.52942802]
 [ 0.31768452]
 [ 0.09185892]
 [ 0.15654727]
 [ 0.02170144]
 [-2.21816073]
 [ 0.57943011]
 [ 0.19170702]
 [-0.22479802]
 [-0.07099848]
 [ 0.41590672]
 [-2.54934107]
 [-1.39004622]
 [-0.1009685 ]
 [-0.61036326]
 [-0.5608773 ]
 [-0.19965081]]


In [354]:
def postprocess(fold,output,parameter):
    min_value = np.min(output)
    max_value = np.max(output)
    scaled_data = (output - min_value) / (max_value - min_value)

    y_hat = np.empty((fold.shape[0],1))
    
    for i in range((fold).shape[0]):
        
        if scaled_data[i,0] > parameter:
            y_hat[i,0] = 1
        else:
            y_hat[i,0] = 0
    
    return y_hat

In [355]:
y_prob_own = np.dot(X,result)

min_value = np.min(y_prob_own)
max_value = np.max(y_prob_own)

scaled_data = (y_prob_own - min_value) / (max_value - min_value)

In [356]:
y_hat = np.empty((X.shape[0],1))
    
for i in range(X.shape[0]):
        
    if scaled_data[i,0] > 0.55:
        y_hat[i,0] = 1
    else:
        y_hat[i,0] = 0

In [357]:
TP = 0
TN = 0
FP = 0
FN = 0
for i in range(X.shape[0]):
    if (y_hat[i,0] == Y[i,0]) and (y_hat[i,0] == 1 and Y[i,0] == 1):
        TP += 1
    elif (y_hat[i,0] == Y[i,0]) and (y_hat[i,0] == 0 and Y[i,0] == 0):
        TN += 1
    elif (y_hat[i,0] != Y[i,0]) and (y_hat[i,0] == 0 and Y[i,0] == 1):
        FP += 1
    elif (y_hat[i,0] != Y[i,0]) and (y_hat[i,0] == 1 and Y[i,0] == 0):
        FN += 1
print("TP:",TP,"TN:",TN,"FP:",FP,"FN:", FN)

TP: 4289 TN: 16159 FP: 2347 FN: 7205


In [358]:
one_accuracy = TP/(TP+FP)
zero_accuracy = TN/(TN+FN)
print("Estimation of zeros:","%",round(one_accuracy*100))
print("Estimation of ones :","%",round(zero_accuracy*100))

Estimation of zeros: % 65
Estimation of ones : % 69


In [227]:
def postprocess(fold,output,parameter):
    min_value = np.min(output)
    max_value = np.max(output)
    scaled_data = (output - min_value) / (max_value - min_value)

    y_hat = np.empty((fold.shape[0],1))
    
    for i in range((fold).shape[0]):
        
        if scaled_data[i,0] > parameter:
            y_hat[i,0] = 1
        else:
            y_hat[i,0] = 0
    
    return y_hat

In [228]:
tuple_lst = np.empty((1,10))
fold_size = 3000
k = 10

threshold_parameters = [0.1,0.2,0.3,0.4,0.5,0.55,0.6,0.7,0.8,0.9]
random_fold_lst = np.random.choice(np.arange(1,11),k,replace = False)
print(random_fold_lst)

[10  3  7  1  5  8  4  9  6  2]


In [367]:
for parameter in range(len(threshold_parameters)):

    parameter_test_error = 0
    parameter_training_error = 0
        
    for fold in range(len(random_fold_lst)):

        test_response = Y[fold_size*(random_fold_lst[fold]-1):fold_size*(random_fold_lst[fold])]
        training_response = Y[fold_size*(random_fold_lst[fold]):]

        test_fold = X[fold_size*(random_fold_lst[fold]-1):fold_size*(random_fold_lst[fold]),:]
        training_fold = X[fold_size*(random_fold_lst[fold]):,:]
        
        print(fold)
        test_result = newton_raphson(test_response,test_fold,Beta)
        y_prob_test = np.dot(test_fold,test_result)

        training_result = newton_raphson(training_response,training_fold,Beta)
        y_prob_training = np.dot(training_fold,training_result)

        y_hat_test = postprocess(test_fold,y_prob_test,threshold_parameters[parameter])
        y_hat_training = postprocess(training_fold,y_prob_training,threshold_parameters[parameter])

        fold_error_test = np.norm(test_response-y_hat_test)/3000
        fold_error_training = np.norm(training_response-y_hat_training)/3000

        parameter_test_error += fold_error_test
        parameter_training_error += fold_error_training
        
    (Test,Train) = ((parameter_test_error/10),(parameter_training_error/10))
    tuple_lst[1,parameter] = (Test,Train)
    
Overall_result = np.hstack(threshold_parameters,tuple_lst).reshape(2,1)

0
1


LinAlgError: Singular matrix

: 